INSERT INTO USER(LOGIN, ADDED_AT, DESCRIPTION, FIRSTNAME, LASTNAME)
VALUES('vlad', CURRENT_TIMESTAMP(), 'nice guy', 'vlad', 'dracul');

INSERT INTO USER(LOGIN, ADDED_AT, DESCRIPTION, FIRSTNAME, LASTNAME)
VALUES('thor', CURRENT_TIMESTAMP(), 'god', 'thor', 'avenger');
