INSERT INTO USER(LOGIN, ADDED_AT, DESCRIPTION, FIRSTNAME, LASTNAME)
VALUES('vlad', CURRENT_TIMESTAMP(), 'nice guy', 'vlad', 'dracul');

INSERT INTO USER(LOGIN, ADDED_AT, DESCRIPTION, FIRSTNAME, LASTNAME)
VALUES('thor', CURRENT_TIMESTAMP(), 'god', 'thor', 'avenger');

INSERT INTO USER(LOGIN, ADDED_AT, DESCRIPTION, FIRSTNAME, LASTNAME)
VALUES('john', CURRENT_TIMESTAMP(), 'wwe', 'John', 'Cena');

INSERT INTO USER(LOGIN, ADDED_AT, DESCRIPTION, FIRSTNAME, LASTNAME)
VALUES('spidy', CURRENT_TIMESTAMP(), 'avenger', 'Spider', 'Man');

INSERT INTO USER(LOGIN, ADDED_AT, DESCRIPTION, FIRSTNAME, LASTNAME)
VALUES('kurt', CURRENT_TIMESTAMP(), 'man', 'Kurt', 'Angle');

INSERT INTO USER(LOGIN, ADDED_AT, DESCRIPTION, FIRSTNAME, LASTNAME)
VALUES('tiger1', CURRENT_TIMESTAMP(), 'panzer', 'tiger', 'one');

INSERT INTO USER(LOGIN, ADDED_AT, DESCRIPTION, FIRSTNAME, LASTNAME)
VALUES('panther', CURRENT_TIMESTAMP(), 'panzer', 'panther', 'two');

INSERT INTO USER(LOGIN, ADDED_AT, DESCRIPTION, FIRSTNAME, LASTNAME)
VALUES('bat', CURRENT_TIMESTAMP(), 'hero', 'Bat', 'Man');

INSERT INTO USER(LOGIN, ADDED_AT, DESCRIPTION, FIRSTNAME, LASTNAME)
VALUES('captain', CURRENT_TIMESTAMP(), 'COD', 'Captain', 'Price');

INSERT INTO USER(LOGIN, ADDED_AT, DESCRIPTION, FIRSTNAME, LASTNAME)
VALUES('prince', CURRENT_TIMESTAMP(), 'POP', 'Prince', 'OfPersia');

INSERT INTO USER(LOGIN, ADDED_AT, DESCRIPTION, FIRSTNAME, LASTNAME)
VALUES('darth', CURRENT_TIMESTAMP(), 'starwars', 'Darth', 'Vader');

INSERT INTO USER(LOGIN, ADDED_AT, DESCRIPTION, FIRSTNAME, LASTNAME)
VALUES('spitfire', CURRENT_TIMESTAMP(), 'fighter', 'Spit', 'Fire');

INSERT INTO USER(LOGIN, ADDED_AT, DESCRIPTION, FIRSTNAME, LASTNAME)
VALUES('wolf', CURRENT_TIMESTAMP(), 'wild', 'Wild', 'Wolf');
